import { existsSync, mkdirSync, copyFileSync, writeFileSync } from 'node:fs';
import { join, basename, resolve } from 'node:path';
import { execSync, execFileSync, spawnSync } from 'node:child_process';
import { stringify as stringifyYaml } from 'yaml';
import { getArchiveInfo } from './info.js';

export interface ContainerizeOptions {
  outputDir?: string;
  run?: boolean;
}

export interface ContainerizeResult {
  outputDir: string;
  files: string[];
  agentName: string;
  started?: boolean;
}

/**
 * Generate Docker deployment files from a .clawback archive.
 * With --run: also build image + run interactively (OpenClaw wizard handles setup).
 */
export async function containerize(
  archivePath: string,
  options: ContainerizeOptions = {},
): Promise<ContainerizeResult> {
  if (!existsSync(archivePath)) {
    throw new Error(`Archive not found: ${archivePath}`);
  }

  const outputDir = options.outputDir ?? './deploy';
  mkdirSync(outputDir, { recursive: true });

  // Read manifest to get agent name
  const { manifest } = await getArchiveInfo(archivePath);
  const agentName = manifest.agent.name;
  const archiveFilename = basename(archivePath);

  // Validate filename to prevent Dockerfile injection via crafted filenames
  if (/[^a-zA-Z0-9._\-]/.test(archiveFilename)) {
    throw new Error(
      `Archive filename "${archiveFilename}" contains unsafe characters. Rename to use only alphanumeric, dot, dash, or underscore.`,
    );
  }

  // Copy archive into deploy folder
  copyFileSync(archivePath, join(outputDir, archiveFilename));

  // Generate Dockerfile — install git for GitHub-based clawback install
  const dockerfile = `FROM node:22-slim

# Install OpenClaw + Clawback
RUN npm install -g openclaw github:shenyuanv/clawback

# Copy backup archive
COPY ["${archiveFilename}", "/tmp/${archiveFilename}"]

# Restore agent
RUN clawback restore "/tmp/${archiveFilename}" --workspace /workspace --force && \\
    rm "/tmp/${archiveFilename}"

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /workspace

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \\
  CMD openclaw health || exit 1

ENTRYPOINT ["/entrypoint.sh"]
`;

  // Entrypoint: import cron jobs + start gateway in foreground
  // Uses node directly (no systemd/launchd needed in containers)
  // OpenClaw's first-run wizard handles API key/model selection via docker-compose tty
  const entrypoint = `#!/bin/sh
set -e

# Import cron jobs if present
if [ -f /workspace/config/cron-jobs.json ]; then
  echo "Importing cron jobs..."
  openclaw cron import /workspace/config/cron-jobs.json 2>/dev/null || true
fi

# Start gateway in foreground (no service manager needed in Docker)
exec openclaw gateway
`;

  // Generate docker-compose.yml
  const compose = {
    services: {
      agent: {
        build: '.',
        stdin_open: true,
        tty: true,
        volumes: [
          './data:/workspace/memory',
          './config:/workspace/config',
        ],
        restart: 'unless-stopped',
        ports: ['3000:3000'],
      },
    },
  };

  // Generate README
  const readme = `# ${agentName} — Docker Deployment

Generated by [Clawback](https://github.com/shenyuanv/clawback).

## Quick Start

\`\`\`bash
# First run (interactive — OpenClaw setup wizard will ask for model + API key):
docker compose run -it agent

# After setup, run in background:
docker compose up -d
\`\`\`

## Check Status

\`\`\`bash
docker compose logs -f
\`\`\`

## Persistent Data

- \`./data/\` — Agent memory (survives restarts)
- \`./config/\` — OpenClaw config + API keys (created by setup wizard)

## Stopping

\`\`\`bash
docker compose down
\`\`\`
`;

  // Write all files
  writeFileSync(join(outputDir, 'Dockerfile'), dockerfile);
  writeFileSync(join(outputDir, 'entrypoint.sh'), entrypoint);
  writeFileSync(join(outputDir, 'docker-compose.yml'), stringifyYaml(compose));
  writeFileSync(join(outputDir, 'README.md'), readme);

  const files = [
    'Dockerfile',
    'entrypoint.sh',
    'docker-compose.yml',
    'README.md',
    archiveFilename,
  ];

  const result: ContainerizeResult = { outputDir, files, agentName };

  // --run: build and launch interactively
  if (options.run) {
    const absOutputDir = resolve(outputDir);

    // Check docker is available
    try {
      execFileSync('docker', ['compose', 'version'], { stdio: 'pipe' });
    } catch {
      throw new Error(
        'Docker Compose not found. Install Docker and try again, or run manually:\n' +
        `  cd ${outputDir} && docker compose run -it agent`,
      );
    }

    // Build image
    execSync('docker compose build', {
      cwd: absOutputDir,
      stdio: 'inherit',
    });

    // Run interactively — OpenClaw wizard handles setup
    const proc = spawnSync('docker', ['compose', 'run', '-it', 'agent'], {
      cwd: absOutputDir,
      stdio: 'inherit',
    });

    result.started = proc.status === 0;
  }

  return result;
}
