import { existsSync, mkdirSync, copyFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { stringify as stringifyYaml } from 'yaml';
import { getArchiveInfo } from './info.js';

export interface ContainerizeOptions {
  outputDir?: string;
}

export interface ContainerizeResult {
  outputDir: string;
  files: string[];
  agentName: string;
}

/**
 * Generate Docker deployment files from a .clawback archive.
 */
export async function containerize(
  archivePath: string,
  options: ContainerizeOptions = {},
): Promise<ContainerizeResult> {
  if (!existsSync(archivePath)) {
    throw new Error(`Archive not found: ${archivePath}`);
  }

  const outputDir = options.outputDir ?? './deploy';
  mkdirSync(outputDir, { recursive: true });

  // Read manifest to get agent name
  const { manifest } = await getArchiveInfo(archivePath);
  const agentName = manifest.agent.name;
  const archiveFilename = basename(archivePath);

  // Copy archive into deploy folder
  copyFileSync(archivePath, join(outputDir, archiveFilename));

  // Generate Dockerfile
  const dockerfile = `FROM node:22-slim

# Install OpenClaw
RUN npm install -g openclaw

# Copy backup archive
COPY ${archiveFilename} /tmp/${archiveFilename}

# Restore agent
RUN mkdir -p /workspace && \\
    npx clawback restore /tmp/${archiveFilename} --workspace /workspace --force && \\
    rm /tmp/${archiveFilename}

# Write API key from environment at runtime
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

WORKDIR /workspace

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s \\
  CMD openclaw gateway status || exit 1

ENTRYPOINT ["/entrypoint.sh"]
`;

  // Generate entrypoint script (writes env vars to gateway config at runtime)
  const entrypoint = `#!/bin/sh
set -e

# Write API key to gateway config if provided via environment
if [ -n "$ANTHROPIC_API_KEY" ]; then
  mkdir -p /workspace/config
  cat > /workspace/config/gateway.yaml <<EOF
anthropic:
  apiKey: $ANTHROPIC_API_KEY
EOF
fi

# Import cron jobs if present
if [ -f /workspace/config/cron-jobs.json ]; then
  echo "Importing cron jobs..."
  openclaw cron import /workspace/config/cron-jobs.json 2>/dev/null || true
fi

# Start gateway
exec openclaw gateway start
`;

  // Generate docker-compose.yml
  const compose = {
    version: '3.8',
    services: {
      agent: {
        build: '.',
        env_file: '.env',
        volumes: ['./data:/workspace/memory'],
        restart: 'unless-stopped',
        ports: ['3000:3000'],
      },
    },
  };

  // Generate .env.example
  const envExample = `# Required: Your AI provider API key
ANTHROPIC_API_KEY=your-key-here
`;

  // Generate README
  const readme = `# ${agentName} — Docker Deployment

Generated by [Clawback](https://github.com/shenyuanv/clawback).

## Quick Start

1. Copy \`.env.example\` to \`.env\` and fill in your API key:
   \`\`\`bash
   cp .env.example .env
   # Edit .env with your ANTHROPIC_API_KEY
   \`\`\`

2. Start the agent:
   \`\`\`bash
   docker compose up -d
   \`\`\`

3. Check status:
   \`\`\`bash
   docker compose logs -f
   \`\`\`

## Persistent Data

Agent memory is persisted to \`./data/\` via volume mount. This survives container restarts.

## Stopping

\`\`\`bash
docker compose down
\`\`\`
`;

  // Write all files
  writeFileSync(join(outputDir, 'Dockerfile'), dockerfile);
  writeFileSync(join(outputDir, 'entrypoint.sh'), entrypoint);
  writeFileSync(join(outputDir, 'docker-compose.yml'), stringifyYaml(compose));
  writeFileSync(join(outputDir, '.env.example'), envExample);
  writeFileSync(join(outputDir, 'README.md'), readme);

  const files = [
    'Dockerfile',
    'entrypoint.sh',
    'docker-compose.yml',
    '.env.example',
    'README.md',
    archiveFilename,
  ];

  return { outputDir, files, agentName };
}
